package com.Fusion.Btremix.definition.packages

import java.io.ByteArrayOutputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/**
 * Writes a `.dcpkg` archive from a Definition document.
 *
 * This is the inverse of [DevicePackageReader] and is deliberately kept next to it so the container
 * format has a single definition. The generated bytes are validated by the reader in tests.
 */
object DevicePackageWriter {

    fun encode(
        packageId: String,
        version: String,
        definitionJson: String,
        entry: String = DEFAULT_ENTRY,
        assets: List<Pair<String, ByteArray>> = emptyList(),
    ): ByteArray {
        val output = ByteArrayOutputStream()
        ZipOutputStream(output).use { zip ->
            zip.writeEntry(PACKAGE_ENTRY, packageJson(packageId, version, entry).toByteArray(Charsets.UTF_8))
            zip.writeEntry(entry, definitionJson.toByteArray(Charsets.UTF_8))
            assets.forEach { (name, bytes) -> zip.writeEntry("assets/$name", bytes) }
        }
        return output.toByteArray()
    }

    fun packageJson(packageId: String, version: String, entry: String = DEFAULT_ENTRY): String = buildString {
        append("{\n")
        append("  \"packageFormat\": ${DevicePackageFormat.CURRENT},\n")
        append("  \"id\": \"$packageId\",\n")
        append("  \"version\": \"$version\",\n")
        append("  \"entry\": \"$entry\"\n")
        append("}\n")
    }

    const val DEFAULT_ENTRY: String = "definition.json"
    private const val PACKAGE_ENTRY = "package.json"

    private fun ZipOutputStream.writeEntry(name: String, bytes: ByteArray) {
        putNextEntry(ZipEntry(name))
        write(bytes)
        closeEntry()
    }
}
