package com.fusion.melodyLinkNeo.melody.api

import com.fusion.melodyLinkNeo.definition.json.JsonParser
import com.fusion.melodyLinkNeo.definition.json.JsonValue
import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * M3.-1 acceptance: the derived template is a parseable, structurally complete `WhitelistConfigDTO`
 * with every capability switch off and no leftover identity from the device it was sampled from.
 *
 * The file is generated by `tools/derive-whitelist-template.ps1` from a real on-device
 * `all_whitelist` export; a hand-edited or truncated asset fails here instead of on the phone.
 */
class MelodyWhitelistTemplateTest {

    private val templateText: String by lazy { templateFile().readText() }
    private val template: Map<String, JsonValue> by lazy { JsonParser.parse(templateText).asObject() }
    private val function: Map<String, JsonValue> by lazy { template.getValue("function").asObject() }

    /** The host's own `WhitelistConfigDTO$Function` field count, observed on Melody 17.6.3. */
    private val expectedFunctionFields = 135

    /** Enabled at build time only for the battery companion parameter; everything else is off. */
    private val keptParameters = mapOf("batteryRadix" to 10.0)

    @Test
    fun template_parsesAndKeepsTheFullHostFieldSet() {
        assertEquals(expectedFunctionFields, function.size)
        assertTrue(function.keys.containsAll(
            listOf(
                "batteryInfo", "batteryRadix", "equalizer", "noiseReductionMode",
                "gameMode", "spatialTypes", "aiTranslate", "autoFirmwareUpdate",
                "multiDevicesConnect", "leFilterFunctions", "wearDetection", "voiceCommand",
            ),
        ))
    }

    @Test
    fun template_keepsTheDtoShapeButNoDeviceIdentity() {
        listOf(
            "brand", "btDelayReport", "children", "coreFrom", "defaultColor", "function",
            "fuzzyMatchName", "id", "minRssi", "minVersion", "name", "opsPodsVersion",
            "podsVersion", "protocolType", "rssi", "supportRlmDeviceFunction", "supportSpp",
            "type", "uuid",
        ).forEach { assertNotNull("missing $it", template[it]) }

        listOf("id", "name", "brand", "uuid", "type", "children").forEach {
            assertTrue("$it must stay neutral", template.getValue(it) is JsonValue.NullValue)
        }
        assertEquals(false, template.getValue("supportSpp").asBoolean())
    }

    @Test
    fun template_hasNoEnabledCapabilityBit() {
        val enabled = function.filter { (name, value) ->
            val kept = keptParameters[name]
            when (value) {
                is JsonValue.BooleanValue -> value.value
                is JsonValue.NumberValue -> value.raw.toDouble() > 0 && kept != value.raw.toDouble()
                is JsonValue.StringValue -> true
                is JsonValue.Array -> value.values.isNotEmpty()
                is JsonValue.Object -> value.values.isNotEmpty()
                JsonValue.NullValue -> false
            }
        }
        assertTrue("capability bits left on: ${enabled.keys}", enabled.isEmpty())
        assertEquals(10.0, function.getValue("batteryRadix").asNumber()!!, 0.0)
    }

    @Test
    fun template_carriesNoPlaceholderOrSampledIdentityText() {
        assertFalse("placeholder residue", templateText.contains("\"...\""))
        listOf("OPPO", "OnePlus", "Enco", "Buds", "06EC10", "067814", "06F010", "0000079A")
            .forEach { assertFalse("$it leaked into the template", templateText.contains(it)) }
    }

    @Test
    fun template_isUtf8WithoutBomAndLfOnly() {
        val bytes = templateFile().readBytes()
        assertTrue("unexpected BOM", bytes.size < 3 ||
            !(bytes[0] == 0xEF.toByte() && bytes[1] == 0xBB.toByte() && bytes[2] == 0xBF.toByte()))
        assertFalse("CRLF line endings", templateText.contains("\r\n"))
        assertTrue("file must end with a newline", templateText.endsWith("\n"))
    }

    private fun templateFile(): File = CANDIDATES.firstOrNull(File::isFile)
        ?: error("cannot locate melody/whitelist-template.json from ${File("").absolutePath}")

    private fun JsonValue.asObject(): Map<String, JsonValue> =
        (this as? JsonValue.Object)?.values ?: error("expected JSON object, got $this")

    private fun JsonValue.asBoolean(): Boolean? = (this as? JsonValue.BooleanValue)?.value

    private fun JsonValue.asNumber(): Double? = (this as? JsonValue.NumberValue)?.raw?.toDouble()

    private companion object {
        private val CANDIDATES = listOf(
            File("src/main/assets/melody/whitelist-template.json"),
            File("app/src/main/assets/melody/whitelist-template.json"),
            File("btremix/app/src/main/assets/melody/whitelist-template.json"),
        )
    }
}
